### PR TITLE
Update Dinner recipe at the right place

### PR DESCRIPTION
**Pull request by TomoeWang**
Updating Dinner recipe at Dinner

## 🎯 Objective

Updated Dinner recipe at the Dinner section

## 🛠️ Changes made

Recipe, serving, minutes, ingredients 

## 👥 Who needs to review this Pull Request? 

@maxhfine
@TakaHaas 
@CarravitaPC

### CODE REVIEW

**Review by TakaHaas — APPROVED** [review]
Great!

**Review by maxhfine — APPROVED** [review]
Great work moving the dinner recipe to dinner! But you also need to take it out of the breakfast folder!

**Comment by CarravitaPC** [comment]
This looks great!!  Just fix the dinner/breakfast mixup.  Thanks!

**Review by CarravitaPC — APPROVED** [review]
Looks great!  Just fix that dinner/breakfast mix up.  Thanks!

**Review by CarravitaPC — APPROVED** [review]
Looks great now!

**Review by CarravitaPC — APPROVED** [review]
Great job updating to the right place

**Pull request merged**
